### ISSUE TITLE
Unable to open file error

### ISSUE THREAD

**Issue by mrunal2401** [felixrosberg/FaceDancer#30]
I got this error while executing this -"python test_video_swap_multi.py --facedancer_path "./model_zoo/FaceDancer_config_c_HQ.h5" --vid_path "path/to/video.mp4" --swap_source "path/to/source_face.jpg" --vid_output "results/swapped_video.mp4""

"Traceback (most recent call last):
![Screenshot 2023-02-21 at 3 50 30 PM](https://user-images.githubusercontent.com/122784951/220318346-bab80a46-de64-41c2-918e-afeca9f45893.png)

  File "test_video_swap_multi.py", line 28, in <module>
    RetinaFace = load_model(opt.retina_path, compile=False,
  File "/opt/anaconda3/envs/facedancer/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/anaconda3/envs/facedancer/lib/python3.8/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/opt/anaconda3/envs/facedancer/lib/python3.8/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)"

**Comment by felixrosberg** [comment]
Looks like you are missing or specified the wrong path for the face detector. It needs to be downloaded from my HuggingFace.

**Comment by mrunal2401** [comment]
I have downloaded from the link you provided in the [github repository](https://huggingface.co/felixrosberg/RetinaFace)

**Comment by netrunner-exe** [comment]
> I have downloaded from the link you provided in the [github repository](https://huggingface.co/felixrosberg/RetinaFace)

`File signature not found` suggests the file is either corrupted or not in the HDF5 format. Try to redownload the file again.

**Comment by mrunal2401** [comment]
Okay. I'll update you after trying

**Comment by mrunal2401** [comment]
Then also same issue is there

**Comment by kdcyberdude** [comment]
++

**Comment by mrunal2401** [comment]
> ++

??

**Comment by kdcyberdude** [comment]
@mrunal2401 I am facing the same issue. If I use the model after cloning from hugging face. You should individually download the model directly. Then it will work.
