### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by johnrom1243** [felixrosberg/FaceDancer#7]
Ive been getting the following error when trying to run it. 

Traceback (most recent call last):
  File "video_swap/multi_face_single_source.py", line 176, in <module>
    swap(opt)
  File "video_swap/multi_face_single_source.py", line 26, in swap
    tf.config.set_visible_devices(gpus[opt.device_id], 'GPU')
IndexError: list index out of range

**Comment by johnrom1243** [comment]
didnt work, added the command but getting this result:

Traceback (most recent call last):
  File "video_swap/multi_face_single_source.py", line 176, in <module>
    swap(opt)
  File "video_swap/multi_face_single_source.py", line 26, in swap
    tf.config.set_visible_devices(gpus[opt.device_id], 'GPU')
IndexError: list index out of range
